### ISSUE TITLE
no pokemon on random

### ISSUE THREAD

**Issue by ghost** [eramdam/pokemonshow#11]
im not quite sure if this has something to do with the program or something else.
im on artix linux with runit and whenever i run 'pokemonshow' nothing shows up.
it DOES give me a pokemon if i run something like 'pokemonshow quagsire' but nothing comes up when i call a random pokemon.
any help is appreciated.

**Comment by eramdam** [comment]
Looks like I broke/forgot to reimplement the random functionality 😅 
Will look into it as soon as I can!

**Comment by eramdam** [comment]
Should be fixed in 2.0.1

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1409924/163138415-d547a47c-cd12-4127-9794-4e75e552a024.png">

**Comment by ghost** [comment]
ill try it out when im back home, thanks!
